import esbuild from "esbuild";
import process from "process";

const prod = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/cschiller/zhongwen (ported to Obsidian)
*/`;

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  // Provided by Obsidian at runtime — must NOT be bundled.
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  loader: {
    ".u8": "text",
    ".idx": "text",
  },
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await ctx.rebuild();
  process.exit(0);
} else {
  await ctx.watch();
}
