/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/cschiller/zhongwen (ported to Obsidian)
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ZhongwenPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/dictionary.ts
var ZhongwenDictionary = class _ZhongwenDictionary {
  constructor(wordDict, wordIndex) {
    this.wordDict = wordDict;
    this.wordIndex = wordIndex;
    this.cache = {};
  }
  /** Binary search for `needle` over newline-delimited sorted `haystack`. */
  static find(needle, haystack) {
    let beg = 0;
    let end = haystack.length - 1;
    while (beg < end) {
      const mi = Math.floor((beg + end) / 2);
      const i = haystack.lastIndexOf("\n", mi) + 1;
      const mis = haystack.substr(i, needle.length);
      if (needle < mis) {
        end = i - 1;
      } else if (needle > mis) {
        beg = haystack.indexOf("\n", mi + 1) + 1;
      } else {
        return haystack.substring(i, haystack.indexOf("\n", mi + 1));
      }
    }
    return null;
  }
  /** Parse a raw dict line into a DictEntry, or null if malformed. */
  static parseLine(line, match) {
    const m = line.match(/^([^\s]+?)\s+([^\s]+?)\s+\[(.*?)\]?\s*\/(.+)\//);
    if (!m)
      return null;
    return {
      traditional: m[1],
      simplified: m[2],
      pinyin: m[3],
      definitions: m[4].split("/").map((d) => d.trim()).filter(Boolean),
      match
    };
  }
  /**
   * Greedy longest-match search starting at the head of `word`.
   * Tries the full string, then trims one char at a time off the end,
   * exactly like the original extension. Returns the matched entries
   * (longest-match entries first) and the matched length.
   */
  wordSearch(word, max) {
    const dict = this.wordDict;
    const index = this.wordIndex;
    const maxTrim = max || 7;
    const entries = [];
    let count = 0;
    let maxLen = 0;
    let more = false;
    outer:
      while (word.length > 0) {
        let ix = this.cache[word];
        if (!ix) {
          const found = _ZhongwenDictionary.find(word + ",", index);
          if (!found) {
            this.cache[word] = [];
            word = word.substr(0, word.length - 1);
            continue;
          }
          ix = found.split(",");
          this.cache[word] = ix;
        }
        for (let j = 1; j < ix.length; ++j) {
          const offset = parseInt(ix[j], 10);
          const nl = dict.indexOf("\n", offset);
          const line = dict.substring(offset, nl === -1 ? void 0 : nl);
          if (count >= maxTrim) {
            more = true;
            break outer;
          }
          ++count;
          if (maxLen === 0) {
            maxLen = word.length;
          }
          const entry = _ZhongwenDictionary.parseLine(line, word);
          if (entry)
            entries.push(entry);
        }
        word = word.substr(0, word.length - 1);
      }
    if (entries.length === 0)
      return null;
    return { entries, matchLen: maxLen, more };
  }
};

// src/pinyin.ts
var COMBINING = {
  1: "\u0304",
  // macron
  2: "\u0301",
  // acute
  3: "\u030C",
  // caron
  4: "\u0300",
  // grave
  5: ""
};
var TONE_COLOR_VARS = {
  1: "var(--color-red, #d93025)",
  2: "var(--color-orange, #e8711a)",
  3: "var(--color-green, #1a7f37)",
  4: "var(--color-blue, #1a56db)",
  5: "var(--text-muted)"
};
function parseSyllable(s) {
  return s.match(/([^AEIOU:aeiou]*)([AEIOUaeiou:]+)([^aeiou:]*)([1-5])/);
}
function tonify(vowels, tone) {
  if (vowels === "ou") {
    return "o" + COMBINING[tone] + "u";
  }
  let text = "";
  let tonified = false;
  for (let i = 0; i < vowels.length; i++) {
    const c = vowels.charAt(i);
    text += c;
    if (c === "a" || c === "e") {
      text += COMBINING[tone];
      tonified = true;
    } else if (i === vowels.length - 1 && !tonified) {
      text += COMBINING[tone];
      tonified = true;
    }
  }
  return text.replace(/u:/, "\xFC");
}
function toPinyinSyllables(syllables) {
  const out = [];
  const parts = syllables.replace(/([1-5])(?=[a-zA-Zü:])/g, "$1 ").split(/[\s·]+/);
  for (const syllable of parts) {
    if (!syllable)
      continue;
    if (syllable === ",") {
      out.push({ text: ",", tone: 5 });
      continue;
    }
    if (syllable === "r5") {
      out.push({ text: "r", tone: 5 });
      continue;
    }
    if (syllable === "xx5") {
      out.push({ text: "?", tone: 5 });
      continue;
    }
    const m = parseSyllable(syllable);
    if (!m) {
      out.push({ text: syllable, tone: 5 });
      continue;
    }
    const tone = parseInt(m[4], 10);
    out.push({ text: m[1] + tonify(m[2], tone) + m[3], tone });
  }
  return out;
}
function toPinyinText(syllables) {
  return toPinyinSyllables(syllables).map((s) => s.text).join(" ").replace(/\s+,/g, " ,");
}

// src/editor-extension.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");

// src/segmenter.ts
var MAX_WORD_LEN = 7;
function isChineseChar(cp) {
  return cp === 9675 || // ○
  13312 <= cp && cp <= 40959 || // CJK + Ext A
  63744 <= cp && cp <= 64255 || // CJK Compatibility Ideographs
  65313 <= cp && cp <= 65338 || // fullwidth A-Z
  65345 <= cp && cp <= 65370 || // fullwidth a-z
  55296 <= cp && cp <= 57343;
}
function chineseWindowAt(text, pos) {
  if (pos < 0 || pos >= text.length)
    return "";
  if (!isChineseChar(text.charCodeAt(pos)))
    return "";
  let end = pos;
  while (end < text.length && end - pos < MAX_WORD_LEN && isChineseChar(text.charCodeAt(end))) {
    end++;
  }
  return text.slice(pos, end);
}
function segmentAtPos(dict, text, pos) {
  const window2 = chineseWindowAt(text, pos);
  if (!window2)
    return null;
  const result = dict.wordSearch(window2);
  if (!result || result.entries.length === 0)
    return null;
  const matchLen = result.matchLen || 1;
  const entries = result.entries.filter((e) => e.match.length === matchLen);
  if (entries.length === 0)
    return null;
  return {
    word: window2.slice(0, matchLen),
    entries,
    start: pos,
    end: pos + matchLen
  };
}

// src/popup.ts
function charCount(s) {
  return Array.from(s).length;
}
var REGISTER_TAGS = /* @__PURE__ */ new Set([
  "idiom",
  "coll.",
  "fig.",
  "lit.",
  "old",
  "dialect",
  "slang",
  "vulgar",
  "derog.",
  "honorific",
  "polite",
  "formal",
  "archaic",
  "abbr.",
  "onom.",
  "neologism",
  "euphemism",
  "loanword",
  "surname",
  "math.",
  "phys.",
  "chem.",
  "bio.",
  "med.",
  "comp.",
  "electr.",
  "mus.",
  "ling.",
  "gram.",
  "astron.",
  "geol.",
  "econ.",
  "law",
  "tw",
  "prc",
  "hk"
]);
var REF_RE = /([㐀-鿿豈-﫿·|]+)?\[([A-Za-z0-9:·,\s]+)\]/g;
function appendPinyin(parent, raw, leadingSpace) {
  const syls = toPinyinSyllables(raw);
  syls.forEach((syl, i) => {
    var _a;
    const span = parent.createSpan({ cls: `zhongwen-tone zhongwen-tone${syl.tone}` });
    span.setText((leadingSpace || i > 0 ? " " : "") + syl.text);
    span.style.color = (_a = TONE_COLOR_VARS[syl.tone]) != null ? _a : "var(--text-normal)";
  });
}
function renderInlineRefs(parent, text) {
  REF_RE.lastIndex = 0;
  let last = 0;
  let m;
  while ((m = REF_RE.exec(text)) !== null) {
    if (m.index > last)
      parent.appendText(text.slice(last, m.index));
    const ref = parent.createSpan({ cls: "zhongwen-ref" });
    if (m[1]) {
      const forms = m[1].split("|");
      ref.createSpan({
        cls: "zhongwen-ref-hanzi",
        text: forms[forms.length - 1]
      });
      appendPinyin(ref, m[2], true);
    } else {
      appendPinyin(ref, m[2], false);
    }
    last = REF_RE.lastIndex;
  }
  if (last < text.length)
    parent.appendText(text.slice(last));
}
function renderDefinitionInto(row, text) {
  let rest = text;
  let m;
  while ((m = rest.match(/^\(([^)]+)\)\s*/)) !== null) {
    const inner = m[1];
    const first = inner.split(/[\s;,]/)[0].toLowerCase();
    if (REGISTER_TAGS.has(first)) {
      row.createSpan({ cls: "zhongwen-tag", text: inner });
      rest = rest.slice(m[0].length);
    } else
      break;
  }
  renderInlineRefs(row, rest);
}
function parseClassifiers(s) {
  const out = [];
  for (const part of s.split(",")) {
    const m = part.trim().match(/^([^\[]+)\[([^\]]+)\]$/);
    if (!m)
      continue;
    const forms = m[1].split("|");
    out.push({ hanzi: forms[forms.length - 1], pinyin: m[2] });
  }
  return out;
}
function renderEntryBlock(root, entry, opts) {
  var _a;
  const header = root.createDiv({ cls: "zhongwen-popup-header" });
  const hanzi = header.createSpan({ cls: "zhongwen-popup-character" });
  hanzi.setText(entry.simplified);
  if (opts.showTraditional && entry.traditional !== entry.simplified) {
    const trad = header.createSpan({ cls: "zhongwen-popup-character zhongwen-popup-trad" });
    trad.setText(entry.traditional);
  }
  const pinyin = header.createSpan({ cls: "zhongwen-popup-pinyin" });
  for (const syl of toPinyinSyllables(entry.pinyin)) {
    const span = pinyin.createSpan({ cls: `zhongwen-tone zhongwen-tone${syl.tone}` });
    span.setText(syl.text + " ");
    span.style.color = (_a = TONE_COLOR_VARS[syl.tone]) != null ? _a : "var(--text-normal)";
  }
  root.createDiv({ cls: "zhongwen-popup-separator" });
  const senses = [];
  const classifiers = [];
  for (const def of entry.definitions) {
    if (def.startsWith("CL:")) {
      classifiers.push(...parseClassifiers(def.slice(3)));
    } else {
      const parts = def.split(/;\s+(?![^(]*\))/);
      for (const p of parts) {
        const trimmed = p.trim();
        if (trimmed)
          senses.push(trimmed);
      }
    }
  }
  const defs = senses.slice(0, 5);
  defs.forEach((def, i) => {
    const row = root.createDiv({ cls: "zhongwen-popup-definition" });
    if (defs.length > 1) {
      row.createSpan({ cls: "zhongwen-popup-definition-number", text: `${i + 1}.` });
    }
    renderDefinitionInto(row, def);
  });
  if (classifiers.length) {
    const row = root.createDiv({ cls: "zhongwen-popup-measure" });
    row.createSpan({ cls: "zhongwen-popup-measure-label", text: "measure word" });
    classifiers.forEach((cl, i) => {
      var _a2;
      const item = row.createSpan({ cls: "zhongwen-popup-measure-item" });
      if (i > 0)
        item.setText(", ");
      item.createSpan({ cls: "zhongwen-popup-measure-hanzi", text: cl.hanzi });
      const py = toPinyinSyllables(cl.pinyin);
      for (const syl of py) {
        const span = item.createSpan({ cls: `zhongwen-tone zhongwen-tone${syl.tone}` });
        span.setText(" " + syl.text);
        span.style.color = (_a2 = TONE_COLOR_VARS[syl.tone]) != null ? _a2 : "var(--text-normal)";
      }
    });
  }
}
function renderPopupDom(entries, opts) {
  const root = document.createElement("div");
  root.className = "zhongwen-popup";
  entries.forEach((entry, i) => {
    if (i > 0) {
      root.createDiv({ cls: "zhongwen-popup-entry-sep" });
    }
    renderEntryBlock(root, entry, opts);
  });
  if (opts.showHSKLevel) {
    const n = charCount(entries[0].simplified);
    root.createDiv({
      cls: "zhongwen-popup-meta",
      text: `${n} character${n === 1 ? "" : "s"}`
    });
  }
  root.createDiv({ cls: "zhongwen-popup-hint", text: 'Press "S" to save' });
  return root;
}
var currentPopup = null;
var currentEntry = null;
var cleanup = null;
var highlightEl = null;
function showHighlight(rects) {
  if (!highlightEl) {
    highlightEl = document.createElement("div");
    highlightEl.className = "zhongwen-highlight";
    document.body.appendChild(highlightEl);
  }
  highlightEl.empty();
  for (let i = 0; i < rects.length; i++) {
    const r = rects[i];
    const box = highlightEl.createDiv({ cls: "zhongwen-highlight-box" });
    box.style.left = `${r.left}px`;
    box.style.top = `${r.top}px`;
    box.style.width = `${r.width}px`;
    box.style.height = `${r.height}px`;
  }
}
function hideHighlight() {
  if (highlightEl) {
    highlightEl.remove();
    highlightEl = null;
  }
}
function getCurrentEntry() {
  return currentEntry;
}
function setCurrentEntry(entry) {
  currentEntry = entry;
}
function destroyPopup() {
  if (cleanup) {
    cleanup();
    cleanup = null;
  }
  if (currentPopup) {
    currentPopup.remove();
    currentPopup = null;
  }
  hideHighlight();
  currentEntry = null;
}
function showPopupAt(entries, x, y, opts) {
  destroyPopup();
  const dom = renderPopupDom(entries, opts);
  dom.style.position = "fixed";
  dom.style.visibility = "hidden";
  document.body.appendChild(dom);
  const rect = dom.getBoundingClientRect();
  const margin = 12;
  const vw = window.innerWidth;
  const vh = window.innerHeight;
  let left = x + margin;
  let top = y + margin;
  if (left + rect.width > vw)
    left = x - rect.width - margin;
  if (top + rect.height > vh)
    top = y - rect.height - margin;
  left = Math.max(4, Math.min(left, vw - rect.width - 4));
  top = Math.max(4, Math.min(top, vh - rect.height - 4));
  dom.style.left = `${left}px`;
  dom.style.top = `${top}px`;
  dom.style.visibility = "visible";
  currentPopup = dom;
  currentEntry = entries[0];
  const onKey = (e) => {
    if (e.key === "Escape")
      destroyPopup();
  };
  const onClick = (e) => {
    if (currentPopup && !currentPopup.contains(e.target)) {
      destroyPopup();
    }
  };
  const onScroll = () => destroyPopup();
  document.addEventListener("keydown", onKey, true);
  document.addEventListener("mousedown", onClick, true);
  window.addEventListener("scroll", onScroll, true);
  cleanup = () => {
    document.removeEventListener("keydown", onKey, true);
    document.removeEventListener("mousedown", onClick, true);
    window.removeEventListener("scroll", onScroll, true);
  };
}
function showSaveFeedback() {
  const popup = currentPopup != null ? currentPopup : document.querySelector(".zhongwen-popup");
  if (!popup)
    return;
  let badge = popup.querySelector(".zhongwen-popup-saved");
  if (!badge) {
    badge = popup.createDiv({ cls: "zhongwen-popup-saved", text: "Saved \u2713" });
  }
  badge.classList.add("zhongwen-popup-saved-show");
  window.setTimeout(() => {
    badge == null ? void 0 : badge.classList.remove("zhongwen-popup-saved-show");
  }, 800);
}

// src/editor-extension.ts
var setHighlight = import_state.StateEffect.define();
var highlightMark = import_view.Decoration.mark({ class: "zhongwen-editor-highlight" });
var highlightField = import_state.StateField.define({
  create() {
    return import_view.Decoration.none;
  },
  update(deco, tr) {
    deco = deco.map(tr.changes);
    for (const e of tr.effects) {
      if (e.is(setHighlight)) {
        deco = e.value ? import_view.Decoration.set([highlightMark.range(e.value.from, e.value.to)]) : import_view.Decoration.none;
      }
    }
    return deco;
  },
  provide: (f) => import_view.EditorView.decorations.from(f)
});
function highlightPlugin(provider) {
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.current = null;
        this.view = view;
        this.onMove = (e) => this.handleMove(e);
        this.onLeave = () => this.clear();
        view.dom.addEventListener("mousemove", this.onMove);
        view.dom.addEventListener("mouseleave", this.onLeave);
      }
      handleMove(e) {
        const dict = provider.getDict();
        if (!dict)
          return this.clear();
        const pos = this.view.posAtCoords({ x: e.clientX, y: e.clientY });
        if (pos == null)
          return this.clear();
        const charCode = this.view.state.doc.sliceString(pos, pos + 1).charCodeAt(0);
        if (isNaN(charCode) || charCode < 13312)
          return this.clear();
        const doc = this.view.state.doc.toString();
        const seg = segmentAtPos(dict, doc, pos);
        if (!seg)
          return this.clear();
        const key = `${seg.start}:${seg.end}`;
        if (key === this.current)
          return;
        this.current = key;
        this.view.dispatch({ effects: setHighlight.of({ from: seg.start, to: seg.end }) });
      }
      clear() {
        if (this.current === null)
          return;
        this.current = null;
        this.view.dispatch({ effects: setHighlight.of(null) });
      }
      destroy() {
        this.view.dom.removeEventListener("mousemove", this.onMove);
        this.view.dom.removeEventListener("mouseleave", this.onLeave);
      }
    }
  );
}
function hoverExtension(provider) {
  return (0, import_view.hoverTooltip)(
    (view, pos) => {
      const dict = provider.getDict();
      if (!dict)
        return null;
      const charCode = view.state.doc.sliceString(pos, pos + 1).charCodeAt(0);
      if (isNaN(charCode) || charCode < 13312)
        return null;
      const doc = view.state.doc.toString();
      const seg = segmentAtPos(dict, doc, pos);
      if (!seg)
        return null;
      return {
        pos: seg.start,
        end: seg.end,
        above: false,
        create() {
          setCurrentEntry(seg.entries[0]);
          const dom = renderPopupDom(seg.entries, provider.getOptions());
          return {
            dom,
            destroy() {
              setCurrentEntry(null);
            }
          };
        }
      };
    },
    { hoverTime: provider.getHoverDelay() }
  );
}
function zhongwenEditorExtension(provider) {
  return [highlightField, highlightPlugin(provider), hoverExtension(provider)];
}

// src/reading-view.ts
var CHINESE_RUN = /[㐀-鿿豈-﫿○]+|[\u{20000}-\u{2FA1F}]+/gu;
function offsetAtPoint(textNode, x, y) {
  const doc = textNode.ownerDocument;
  if (doc.caretPositionFromPoint) {
    const p = doc.caretPositionFromPoint(x, y);
    if (p && p.offsetNode === textNode)
      return p.offset;
  }
  if (doc.caretRangeFromPoint) {
    const r = doc.caretRangeFromPoint(x, y);
    if (r && r.startContainer === textNode)
      return r.startOffset;
  }
  return 0;
}
function makeReadingProcessor(provider) {
  return (el, _ctx) => {
    var _a;
    const panelState = { activeKey: null };
    const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT);
    const textNodes = [];
    let node;
    while (node = walker.nextNode()) {
      const parent = node.parentElement;
      if (parent && parent.closest("code, pre"))
        continue;
      textNodes.push(node);
    }
    for (const textNode of textNodes) {
      const text = (_a = textNode.textContent) != null ? _a : "";
      CHINESE_RUN.lastIndex = 0;
      if (!CHINESE_RUN.test(text))
        continue;
      CHINESE_RUN.lastIndex = 0;
      const frag = document.createDocumentFragment();
      let lastIndex = 0;
      let match;
      while ((match = CHINESE_RUN.exec(text)) !== null) {
        if (match.index > lastIndex) {
          frag.appendChild(
            document.createTextNode(text.slice(lastIndex, match.index))
          );
        }
        const span = document.createElement("span");
        span.className = "zhongwen-hoverable";
        span.textContent = match[0];
        attachHover(span, provider, panelState);
        frag.appendChild(span);
        lastIndex = CHINESE_RUN.lastIndex;
      }
      if (lastIndex < text.length) {
        frag.appendChild(document.createTextNode(text.slice(lastIndex)));
      }
      textNode.replaceWith(frag);
    }
  };
}
function attachHover(span, provider, panelState) {
  const show = (e) => {
    var _a;
    const dict = provider.getDict();
    if (!dict) {
      panelState.activeKey = null;
      return;
    }
    const inner = span.firstChild;
    const runText = (_a = span.textContent) != null ? _a : "";
    let pos = 0;
    if (inner)
      pos = offsetAtPoint(inner, e.clientX, e.clientY);
    if (pos >= runText.length || !isChineseChar(runText.charCodeAt(pos))) {
      pos = 0;
    }
    const seg = segmentAtPos(dict, runText, pos);
    if (!seg) {
      panelState.activeKey = null;
      destroyPopup();
      return;
    }
    const key = `${seg.start}:${seg.end}:${seg.word}`;
    if (key === panelState.activeKey)
      return;
    panelState.activeKey = key;
    showPopupAt(seg.entries, e.clientX, e.clientY, provider.getOptions());
    if (inner) {
      try {
        const range = document.createRange();
        range.setStart(inner, seg.start);
        range.setEnd(inner, Math.min(seg.end, runText.length));
        showHighlight(range.getClientRects());
      } catch (e2) {
      }
    }
  };
  span.addEventListener("mouseenter", show);
  span.addEventListener("mousemove", show);
  span.addEventListener("mouseleave", (e) => {
    const to = e.relatedTarget;
    if (to && to.closest(".zhongwen-popup"))
      return;
    panelState.activeKey = null;
    destroyPopup();
  });
}

// main.ts
var DEFAULT_SETTINGS = {
  wordListNote: "Chinese/Word List",
  showHSKLevel: true,
  showTraditional: false,
  hoverDelayMs: 300,
  enableInEditor: true,
  enableInReadingView: true
};
var ZhongwenPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.dict = null;
    // Mutable array handed to registerEditorExtension; we swap its contents and
    // call workspace.updateOptions() to apply settings changes without reload.
    this.editorExtensions = [];
  }
  async onload() {
    await this.loadSettings();
    this.loadDictionary().catch((e) => {
      console.error("Zhongwen: failed to load dictionary", e);
      new import_obsidian.Notice("Zhongwen: failed to load dictionary (see console)");
    });
    const provider = {
      getDict: () => this.settings.enableInEditor ? this.dict : null,
      getOptions: () => this.popupOptions(),
      getHoverDelay: () => this.settings.hoverDelayMs
    };
    this.editorExtensions.push(zhongwenEditorExtension(provider));
    this.registerEditorExtension(this.editorExtensions);
    this.registerMarkdownPostProcessor(
      makeReadingProcessor({
        getDict: () => this.settings.enableInReadingView ? this.dict : null,
        getOptions: () => this.popupOptions()
      })
    );
    this.registerDomEvent(document, "keydown", (e) => this.onKeyDown(e), true);
    this.addSettingTab(new ZhongwenSettingTab(this.app, this));
  }
  onunload() {
    destroyPopup();
  }
  popupOptions() {
    return {
      showHSKLevel: this.settings.showHSKLevel,
      showTraditional: this.settings.showTraditional
    };
  }
  /** Read cedict_ts.u8 + cedict.idx from the plugin's own folder. */
  async loadDictionary() {
    const dir = this.manifest.dir;
    if (!dir)
      throw new Error("plugin dir unknown");
    const adapter = this.app.vault.adapter;
    const dictText = await adapter.read(
      (0, import_obsidian.normalizePath)(`${dir}/data/cedict_ts.u8`)
    );
    const idxText = await adapter.read(
      (0, import_obsidian.normalizePath)(`${dir}/data/cedict.idx`)
    );
    this.dict = new ZhongwenDictionary(dictText, idxText);
  }
  onKeyDown(e) {
    if (e.key !== "s" && e.key !== "S")
      return;
    const popupVisible = !!document.querySelector(".zhongwen-popup");
    const entry = getCurrentEntry();
    if (!popupVisible || !entry)
      return;
    if (e.ctrlKey || e.metaKey || e.altKey)
      return;
    e.preventDefault();
    e.stopPropagation();
    this.saveWord(entry);
  }
  async saveWord(entry) {
    var _a;
    const path = (0, import_obsidian.normalizePath)(this.settings.wordListNote + ".md");
    const realDef = (_a = entry.definitions.find((d) => !d.startsWith("CL:"))) != null ? _a : "";
    const py = toPinyinText(entry.pinyin);
    const line = `- **${entry.simplified}** (${py}) \u2014 ${realDef}`;
    try {
      const existing = this.app.vault.getAbstractFileByPath(path);
      if (existing instanceof import_obsidian.TFile) {
        const content = await this.app.vault.read(existing);
        const sep = content.endsWith("\n") ? "" : "\n";
        await this.app.vault.modify(existing, content + sep + line + "\n");
      } else {
        const folder = path.contains("/") ? path.slice(0, path.lastIndexOf("/")) : "";
        if (folder && !this.app.vault.getAbstractFileByPath(folder)) {
          await this.app.vault.createFolder(folder).catch(() => {
          });
        }
        await this.app.vault.create(
          path,
          `# Chinese Word List

${line}
`
        );
      }
      showSaveFeedback();
    } catch (err) {
      console.error("Zhongwen: save failed", err);
      new import_obsidian.Notice("Zhongwen: failed to save word (see console)");
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /** Rebuild the CM6 hover extension (e.g. after hover-delay change). */
  refreshEditorExtension() {
    const provider = {
      getDict: () => this.settings.enableInEditor ? this.dict : null,
      getOptions: () => this.popupOptions(),
      getHoverDelay: () => this.settings.hoverDelayMs
    };
    this.editorExtensions.length = 0;
    this.editorExtensions.push(zhongwenEditorExtension(provider));
    this.app.workspace.updateOptions();
  }
};
var ZhongwenSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Word list note path").setDesc('Note where saved words are appended (no ".md"). Folders are created if missing.').addText(
      (text) => text.setPlaceholder("Chinese/Word List").setValue(this.plugin.settings.wordListNote).onChange(async (value) => {
        this.plugin.settings.wordListNote = value.trim() || DEFAULT_SETTINGS.wordListNote;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show meta row").setDesc("Show character count under definitions. (HSK dataset is not bundled \u2014 see README.)").addToggle(
      (t) => t.setValue(this.plugin.settings.showHSKLevel).onChange(async (v) => {
        this.plugin.settings.showHSKLevel = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show traditional character").setDesc("Show the traditional form next to the simplified form when they differ.").addToggle(
      (t) => t.setValue(this.plugin.settings.showTraditional).onChange(async (v) => {
        this.plugin.settings.showTraditional = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Hover delay (ms)").setDesc("How long to hover before the popup appears (editor view).").addSlider(
      (s) => s.setLimits(100, 800, 50).setValue(this.plugin.settings.hoverDelayMs).setDynamicTooltip().onChange(async (v) => {
        this.plugin.settings.hoverDelayMs = v;
        await this.plugin.saveSettings();
        this.plugin.refreshEditorExtension();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable in editor").setDesc("Show the popup while editing (Live Preview / Source mode).").addToggle(
      (t) => t.setValue(this.plugin.settings.enableInEditor).onChange(async (v) => {
        this.plugin.settings.enableInEditor = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable in reading view").setDesc("Show the popup in rendered (reading) view.").addToggle(
      (t) => t.setValue(this.plugin.settings.enableInReadingView).onChange(async (v) => {
        this.plugin.settings.enableInReadingView = v;
        await this.plugin.saveSettings();
      })
    );
  }
};
